// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddPredictionEnginePool<MLModel1.ModelInput, MLModel1.ModelOutput>()
    .FromFile("MLModel1.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
builder.Services.AddScoped<PredictionController>();
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});


app.MapGet("/", () => "ML.NET Model Builder API is running.");
app.MapControllers();

// Run app
app.Run();
